# This workflow runs systests in various configurations for the WRES service

name: Systests 

on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        description: 'Build description'

  # Runs systests after a successful build
  workflow_run:
    workflows: [Build]
    types: 
      - completed
      
run-name: Systests for commit ${{ github.event.workflow_run.head_commit.id }} triggered by build ${{ github.event.workflow_run.id }}

jobs:
  systests:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      run: echo "step 1"

    # Set env variables for zip versions
    - name: Set git envs
      run: echo "step 2"

       
    # Run systests
    - name: Systests With Externalized Writers
      run: echo "step 13"

    # Run systests
    - name: Systests With Self-contained Process
      run: run: echo "step 14"
